### ISSUE TITLE
Remmina system tray icon

### ISSUE THREAD

**Issue by nuxster** [naib864/regolith-midnight-gtk#3]
Hello! 
Remmina's developers have broken the system tray icon [this](https://github.com/ubuntu/yaru/issues/2940). 
Is it possible to fix this at the theme level?
remmina's developer comment [this](https://gitlab.com/Remmina/Remmina/-/issues/2502#note_616336775)

**Comment by naib864** [comment]
I'm not sure what the problem is, but the theme does not mess with the system tray icons so I can't change anything regarding system tray.
